### ISSUE TITLE
python3 pyqt4 does not provide QString by default

### ISSUE THREAD

**Issue by lmamane** [kiorky/spynner#104]
Leading to error message:
ImportError: cannot import name 'QString' from 'PyQt4.QtCore' (/usr/lib/python3/dist-packages/PyQt4/QtCore.cpython-37m-x86_64-linux-gnu.so)

Work-around: Before loading spynner, do:
>>> import sip
>>> sip.setapi('QString', 1)

These lines should probably just be added to spynner itself.

**Comment by kiorky** [comment]
spynner wont have py3 support.
